project:
  type: book

book:
  title: "ME493 - Methods of Data-Driven Control"
  author: "Benjamin Aziel"
  date: today
  repo-url: https://github.com/destrospooder/data_driven_methods
  chapters:
    - index.qmd
    - ch1.qmd
    - ch2.qmd
    - ch3.qmd
    - ch4.qmd
    - ch5.qmd
    - references.qmd
  downloads: [pdf, epub]
  navbar:
    background: secondary
    search: true

bibliography: references.bib

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    grid:
      sidebar-width: 300px
  pdf:
    documentclass: scrreprt



