# Preface {.unnumbered}

Documentation of the independent study ME493: Methods of Data-Driven Control, taken during Spring 2024.

**Instructor:** Dirk M. Luchtenburg<br/>
**Co-conspirators:** Sohaib Bhatti, Khushant Khurana, Eunkyu (Q) Kim, Sonam Okuda<br/>
**Email:** dirk.luchtenburg@cooper.edu<br/>

**Description:**<br/>
This independent study provides an introduction to state-of-the-art methods employed in the field of data-driven engineering. Data-driven methods such as the proper orthogonal decomposition and the dynamic mode decomposition are used in a variety of fields including fluid dynamics, climate analysis, mixing problems, the study of infectious diseases, etc. Data-driven methods rely heavily on concepts from linear algebra, calculus, probability, and statistics. We will review these essential elements and develop a hands-on understanding of a selection of data-driven methods. The study culminates with an application of some method(s) to a practical problem which is to be carefully detailed in a technical report.

Referenced texts include the following:

- @strang2019linear <br/>
- @brunton2022data <br/>
- @boyd2018introduction <br/>
- @geron2022hands <br/>
- @sutton2018reinforcement